# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mémoire de l'attaque criminelle de Kyoto Animation
# email:
description: >- # this means to ignore newlines until "baseurl:"
  Une analyse complète des événements, impacts et conséquences de l'attaque criminelle tragique contre Kyoto Animation en 2019.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lameur.github.io/EMC-Kyoto-Animation/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Lameur

# Build settings
theme: minima

# Theme settings
minima:
  skin: auto

# Pages de l'en-tête
header_pages:
  - chronologie.md
  - victimes.md
  - juridique.md
  - sources.md
  - a-propos.md

plugins:
  - jekyll-spaceship
  - jekyll-avatar
  - jekyll-responsive-magick
  - jekyll-include-cache
  - jekyll-toc
  - jekyll-assets

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

exclude:
  - .
include:
  - _static

source: _static

collections:
  default:
    output: true
    permalink: /:path/


## Plugins configuration

# _config.yml

source_maps: true # false on JEKYLL_ENV=production
destination: "/assets"
compression: true
gzip: true
defaults:
  js: { integrity: true } # true on JEKYLL_ENV=production
  css: { integrity: true } # true on JEKYLL_ENV=production
  img: { integrity: true } # true on JEKYLL_ENV=production
caching:
  path: ".jekyll-cache/assets"
  type: file # Possible values: memory, file
  enabled: true
  # --
# Assets you wish to always have compiled.
#   This can also be combined with raw_precompile which
#   copies assets without running through the pipeline
#   making them ultra fast.
# --
precompile: []
raw_precompile: []

# --
# baseurl: whether or not to append site.baseurl
# destination: the folder you store them in on the CDN.
# url: the CDN url (fqdn, or w/ identifier).
# --
cdn:
  baseurl: false
  destination: false
  url: null
# --
# These are all default. No need to add them
#   Only use this if you have more.
# --
sources:
  - assets/css
  - assets/fonts
  - assets/videos
  - assets/javascript
  - assets/video
  - assets/image
  - assets/img
  - assets/js

plugins:
  css: { autoprefixer: {}}
  img: { optim: {}}

responsive:
  widths: [400, 500, 700, 900, 1000]
  heights: [400, 500, 700, 900, 1000]
  quality: 100
  format: webp
  verbose: true

# Where things are
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - emoji-processor
    - element-processor
    - media-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ["$", "$"]
          - ['\(', '\)']
        displayMath:
          - ["$$", "$$"]
          - ['\[', '\]']
      svg:
        fontCache: "global"
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: [] # include patterns for math expressions checking (regexp)
      exclude: [] # exclude patterns for math expressions checking (regexp)
  plantuml-processor:
    mode: pre-fetch # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: "plantuml!"
      custom: ["@startuml", "@enduml"]
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: pre-fetch # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: "mermaid!"
      custom: ["@startmermaid", "@endmermaid"]
    config:
      theme: dark
    src: https://mermaid.ink/svg/
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/
